apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traffic-monitor
  labels:
    app: traffic-monitor
spec:
  template:
    metadata:
      labels:
        app: traffic-monitor
    spec:
      hostNetwork: true
      containers:
      - name: traffic-monitor
        image: "luguoxiang/traffic-monitor:1.0"
        imagePullPolicy: Always
        command:
        - "./traffic-monitor"
        - "-alsologtostderr"   
        env:
        - name: VIZ_METRICS_PORT
          value: '32466'
